onedrive:
  client_id: "your_client_id"
  client_secret: "your_client_secret"
  redirect_uri: "your_redirect_uri"
  scope: "files.readwrite offline_access"
log:
  path: "the_path_of_your_log"
  max_size: 10
  max_backups: 3
  level: "info"
  compress: true
backup:
  root_dir: "the_root_dir_of_your_backup"
  output_dir: "the_output_dir_of_your_backup"
  password: "your_password"
  force_full_backup: false
  cron: "0 0 * * *"