onedrive:
  client_id: "your_client_id"
  client_secret: "your_client_secret"
  redirect_uri: "your_redirect_uri"
  scope: "files.readwrite offline_access"
log:
  path: "./logs/auto-backup.log"
  max_size: 10
  max_backups: 3
  level: "info"
  compress: true
backup:
  root_dir: "/root/backup"
  output_dir: "/root/output"
  password: "your_password"
  force_full_backup: false
  cron: "0 0 * * *"